apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-ruby
    version: v1
  name: demo-ruby
  namespace: lowrider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-ruby
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: demo-ruby
        version: v1
    spec:
      containers:
      - env:
        - name: SECRET_KEY_BASE
          value: development_test_key
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              key: database-name
              name: postgresql
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-admin-password
              name: postgresql
        - name: DATABASE_URL
          value: postgresql://postgresql.lowrider.svc:5432
        image: quay.io/gsalgadoartola/demo-ruby:1.0.rc-16
        imagePullPolicy: IfNotPresent
        name: demo-ruby
        ports:
        - containerPort: 3000
          name: http-api
          protocol: TCP
        resources:
          limits:
            cpu: 150m
            memory: 512Mi
          requests:
            cpu: 20m
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
