---
apiVersion: batch/v1
kind: Job
metadata:
  name: demo-ruby-db-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - env:
        - name: SECRET_KEY_BASE
          value: development_test_key
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              key: database-name
              name: postgresql
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-admin-password
              name: postgresql
        - name: DATABASE_URL
          value: postgresql://postgresql.lowrider.svc:5432
        - name: DISABLE_DATABASE_ENVIRONMENT_CHECK
          value: "1"
        - name: DEVISE_SECRET_KEY
          value: "26c581c7b303b021c6139ca0bc2134dd78a1047d0c73e8458c44fa0e3e4e2f9b15ccda8f5a0b556c18836f98eced3fef7b35833c5f1ae1452cb71bbb08bcbf1f"
        name: demo-ruby-db-migrate
        image: quay.io/xmartlabs/demo-ruby:1.0.rc-19
        command:
          - "/bin/bash"
          - "-c"
          - "bundle exec rails db:migrate"
      restartPolicy: Never
  backoffLimit: 2
