apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-app
    version: v1
  name: demo-app
spec:
  ports:
  - name: http-api
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-app
    version: v1
  type: ClusterIP
